import { useState } from "react";
import { SparklesIcon } from "@heroicons/react/24/solid";

import PlaygroundCanvas from "./canvas/canvas";
import { usePlaygroundDraft } from "./state/persist";

export type PlaygroundAuthMode = "required" | "anonymous";

export type PlaygroundProps = {
  /**
   * URL the chat adapter posts each turn against. Externalised so the same
   * component tree can re-embed in the marketing site against a public,
   * rate-limited variant of the endpoint later.
   */
  chatEndpoint: string;
  /**
   * `required` — assume the parent shell has already enforced authentication
   * (current fabro-web routes do this via `AppShell`).
   * `anonymous` — anonymous embed mode for a future marketing-site island;
   * not used by fabro-web today.
   */
  authMode: PlaygroundAuthMode;
};

/**
 * The playground feature surface, deliberately framed as a standalone
 * component tree so it can later be lifted into the Astro marketing site
 * as a React island (engineering-as-marketing). It must not depend on
 * `AppShell`, react-router context, or any of fabro-web's app-wide stores;
 * any cross-cutting concern (chat endpoint, auth mode, theme) flows in
 * through props.
 *
 * Layout mirrors `/ask-fabro`: workspace on the left, the AskFabroSidebar-
 * style assistant column on the right.
 *
 * v1 wires the canvas + state; the chat sidebar is a placeholder slot here
 * until chunk 7 swaps in the real playground-flavoured runtime adapter.
 */
export default function Playground({
  chatEndpoint: _chatEndpoint,
  authMode: _authMode,
}: PlaygroundProps) {
  const { draft } = usePlaygroundDraft();
  // Sidebar starts open: the playground is built around the chat, so it
  // doesn't make sense to hide it on first visit. The toggle still exists
  // for users who want a full-width canvas to inspect a busy graph.
  const [isChatOpen, setChatOpen] = useState(true);

  return (
    <div className="relative isolate -mx-4 -my-6 flex h-[calc(100%+3rem)] sm:-mx-6 lg:-mx-8">
      <main className="flex h-full min-h-0 flex-1 flex-col gap-3 p-3">
        <header className="flex items-center gap-3 px-2">
          <h1 className="text-base font-semibold text-fg">Playground</h1>
          <span className="text-sm text-fg-3">
            {/* Workflow name is auto-generated by the model; until then we
                show a discreet placeholder. */}
            {draft.name === "untitled" ? "untitled workflow" : draft.name}
          </span>
          <div className="ml-auto flex items-center gap-2">
            {!isChatOpen && (
              <button
                type="button"
                onClick={() => setChatOpen(true)}
                className="inline-flex items-center gap-1.5 rounded-md bg-overlay px-2.5 py-1.5 text-sm font-medium text-fg-2 ring-1 ring-line-strong transition-colors hover:bg-overlay-strong hover:text-fg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-500"
              >
                <SparklesIcon className="size-4 text-teal-300" />
                Ask Fabro
              </button>
            )}
          </div>
        </header>

        <div className="flex min-h-0 flex-1 flex-col gap-3">
          <PlaygroundCanvas draft={draft} />
        </div>
      </main>

      <PlaceholderChatSlot
        isOpen={isChatOpen}
        onClose={() => setChatOpen(false)}
      />
    </div>
  );
}

/**
 * Right-docked column that will host the playground-flavoured AskFabro
 * sidebar in chunk 7. Kept as a separate component so that swap is a
 * surgical edit. Layout / animation / handle styling intentionally mirrors
 * `AskFabroSidebar` so the visual diff at swap time is minimal.
 */
function PlaceholderChatSlot({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) {
  return (
    <aside
      aria-label="Ask Fabro"
      aria-hidden={!isOpen}
      style={{ width: isOpen ? 420 : 0 }}
      className="h-full shrink-0 overflow-hidden transition-[width] duration-300 ease-[cubic-bezier(0.16,1,0.3,1)]"
    >
      <div
        className="flex h-full flex-col border-l border-line bg-panel/40 backdrop-blur-sm"
        style={{ width: 420 }}
      >
        <header className="flex h-12 shrink-0 items-center justify-between px-3">
          <span className="text-xs font-medium uppercase tracking-wider text-fg-muted">
            Ask Fabro
          </span>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close assistant"
            className="inline-flex size-7 items-center justify-center rounded-md text-fg-3 transition-colors hover:bg-overlay hover:text-fg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-500"
          >
            <svg viewBox="0 0 16 16" fill="none" className="size-3.5">
              <path
                d="M3.5 3.5l9 9M12.5 3.5l-9 9"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </svg>
          </button>
        </header>
        <div className="flex min-h-0 flex-1 items-center justify-center p-6 text-center">
          <p className="max-w-xs text-sm leading-relaxed text-fg-muted">
            The playground chat lands in chunk 7. Until then this column is a
            placeholder so the canvas layout looks like its final self.
          </p>
        </div>
      </div>
    </aside>
  );
}
