/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommandOutputStream } from './command-output-stream';

/**
 * Byte-offset command log slice.
 */
export interface CommandLogResponse {
    'stream': CommandOutputStream;
    /**
     * Actual byte offset used for this slice.
     */
    'offset': number;
    /**
     * Byte offset for the next tail request.
     */
    'next_offset': number;
    /**
     * Total bytes currently available for the stream.
     */
    'total_bytes': number;
    /**
     * Base64-encoded raw log bytes.
     */
    'bytes_base64': string;
    /**
     * Whether the stream is finalized.
     */
    'eof': boolean;
    'cas_ref': string | null;
    /**
     * Whether the sandbox provided live output while the command was running.
     */
    'live_streaming': boolean;
}



