/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GitlabIntegrationSettings {
    'enabled': boolean;
    'strategy': GitlabIntegrationSettingsStrategyEnum;
    'base_url'?: string | null;
    'client_id'?: string | null;
}

export const GitlabIntegrationSettingsStrategyEnum = {
    TOKEN: 'token',
    APP: 'app'
} as const;

export type GitlabIntegrationSettingsStrategyEnum = typeof GitlabIntegrationSettingsStrategyEnum[keyof typeof GitlabIntegrationSettingsStrategyEnum];
