/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redacted summary of the GitLab install strategy selected during browser install.
 */
export interface InstallGitlabSummary {
    'strategy': InstallGitlabSummaryStrategyEnum;
    'base_url': string;
    'client_id'?: string;
    'allowed_usernames'?: Array<string>;
    'allowed_groups'?: Array<string>;
}

export const InstallGitlabSummaryStrategyEnum = {
    TOKEN: 'token',
    APP: 'app'
} as const;

export type InstallGitlabSummaryStrategyEnum = typeof InstallGitlabSummaryStrategyEnum[keyof typeof InstallGitlabSummaryStrategyEnum];
