/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for interrupting a live agent stage\'s model turn.
 */
export interface InterruptRunRequest {
    /**
     * The agent stage to interrupt: its stage identifier (`node_id@visit`) or its node name. Omit it to interrupt the run\'s one live agent stage.
     */
    'stage'?: string;
    /**
     * The stage\'s next input once its turn is stopped. Omit it to let the stage wait for the next steer message.
     */
    'text'?: string;
}
