/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for linking an existing pull request or merge request to a run.
 */
export interface LinkRunPullRequestRequest {
    /**
     * Pull request or merge request URL to associate with the run. Supports GitHub PR URLs and GitLab MR URLs.
     */
    'html_url': string;
}
