/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One of Fabro\'s platform records of a Petri run, as stored: the record\'s JSON tagged by `kind`, its position in the run\'s platform record sequence, and the Petri stage it belongs to when it belongs to one.
 */
export interface PetriPlatformRecord {
    /**
     * The record\'s position in the run\'s platform records, from 1.
     */
    'seq': number;
    /**
     * Milliseconds since the Unix epoch when the record was stored.
     */
    'recorded_at': number;
    /**
     * The platform record itself, tagged by `kind`.
     */
    'record': { [key: string]: any; };
    /**
     * The Petri execution the record belongs to, with `firing`.
     */
    'execution'?: number;
    /**
     * The Petri firing the record belongs to, with `execution`.
     */
    'firing'?: number;
}
