/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One platform record to store for the run.
 */
export interface PetriPlatformRecordAppendRequest {
    /**
     * The platform record, tagged by `kind`.
     */
    'record': { [key: string]: any; };
    /**
     * The Petri execution the record belongs to, with `firing`.
     */
    'execution'?: number;
    /**
     * The Petri firing the record belongs to, with `execution`.
     */
    'firing'?: number;
}
