/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One stored line of a Petri log: the record as JSON, with `seq` and `recorded_at` lifted out of it so the store can key and index without reading into the JSON. What the store hands back equals what it was given as a JSON value.
 */
export interface PetriRecord {
    /**
     * The record\'s position in its log, from 0.
     */
    'seq': number;
    /**
     * Milliseconds since the Unix epoch when Petri appended the record.
     */
    'recorded_at': number;
    /**
     * The record itself, stored and read back unchanged.
     */
    'record': { [key: string]: any; };
}
