/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PetriRecord } from './petri-record';

/**
 * One batch of records for one Petri log.
 */
export interface PetriAppendRequest {
    /**
     * The owner id the worker holds the run\'s writer lease with.
     */
    'owner': string;
    'records': Array<PetriRecord>;
}
