/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PreparedStepOneOf {
    'type': PreparedStepOneOfTypeEnum;
    'script': string;
    'env'?: { [key: string]: string; };
}

export const PreparedStepOneOfTypeEnum = {
    SCRIPT: 'script'
} as const;

export type PreparedStepOneOfTypeEnum = typeof PreparedStepOneOfTypeEnum[keyof typeof PreparedStepOneOfTypeEnum];
