/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * LLM provider identifier.
 */

export const Provider = {
    ANTHROPIC: 'anthropic',
    OPENAI: 'openai',
    GEMINI: 'gemini',
    KIMI: 'kimi',
    ZAI: 'zai',
    MINIMAX: 'minimax',
    INCEPTION: 'inception',
    OPENAI_COMPATIBLE: 'openai_compatible'
} as const;

export type Provider = typeof Provider[keyof typeof Provider];



