/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestProvider } from './pull-request-provider';

/**
 * Minimal provider-aware pull request link associated with a run.
 */
export interface PullRequestLink {
    'provider': PullRequestProvider;
    /**
     * Repository owner or namespace path. GitLab namespaces may be nested.
     */
    'owner_path': string;
    'repo': string;
    'number': number;
    'html_url': string;
}
