/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestDetailsTimestamps } from './pull-request-details-timestamps';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestUser } from './pull-request-user';

/**
 * Live provider pull request or merge request fields retrieved successfully.
 */
export interface PullRequestDetails {
    'title': string;
    'body'?: string | null;
    'state': string;
    'draft': boolean;
    'merged': boolean;
    'merged_at'?: string | null;
    'mergeable'?: boolean | null;
    /**
     * Lines added when the provider reports reliable line stats; `null` when unknown.
     */
    'additions': number | null;
    /**
     * Lines deleted when the provider reports reliable line stats; `null` when unknown.
     */
    'deletions': number | null;
    'changed_files': number;
    'author': PullRequestUser;
    'head_branch': string;
    'base_branch': string;
    'timestamps': PullRequestDetailsTimestamps;
}
