/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckRun } from './check-run';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequest } from './pull-request';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestDetailsTimestamps } from './pull-request-details-timestamps';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestUser } from './pull-request-user';

/**
 * Stored pull request record plus live GitHub-enriched fields when available.
 */
export interface PullRequestDetails {
    'pull_request': PullRequest;
    'state'?: string | null;
    'draft'?: boolean | null;
    'merged'?: boolean | null;
    'merged_at'?: string | null;
    'mergeable'?: boolean | null;
    'additions'?: number | null;
    'deletions'?: number | null;
    'changed_files'?: number | null;
    'comments'?: number | null;
    'checks'?: Array<CheckRun> | null;
    'author'?: PullRequestUser | null;
    'timestamps'?: PullRequestDetailsTimestamps | null;
}
