/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response returned after rewind creates and starts a new run.
 */
export interface RewindResponse {
    'source_run_id': string;
    'new_run_id': string;
    /**
     * The checkpoint the rewind was resolved to, as `@ordinal`.
     */
    'target': string;
    'checkpoint_sha': string;
    'execution': number;
    'firing': number;
    'archived': boolean;
    'archive_error'?: string | null;
}
