/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpServerSettings } from './mcp-server-settings';

export interface RunAgentSettings {
    'fabro_tools': boolean;
    /**
     * Extra skill discovery directories, searched after the convention directories. Relative entries resolve against the repository root.
     */
    'skill_dirs': Array<string>;
    'mcps': { [key: string]: McpServerSettings; };
}
