/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A checkpoint Fabro recorded for the run: when, at which node, and the commit the workspace was checkpointed at, when it was committed.
 */
export interface RunCheckpoint {
    /**
     * When the checkpoint was recorded.
     */
    'timestamp': string;
    /**
     * The node the checkpoint was recorded for.
     */
    'current_node': string;
    /**
     * SHA of the git commit created at this checkpoint.
     */
    'git_commit_sha'?: string;
}
