/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BilledTokenCounts } from './billed-token-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { BillingStageRef } from './billing-stage-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelReference } from './model-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { StageState } from './stage-state';

/**
 * Token counts and billed totals for a single stage within a run.
 */
export interface RunBillingStage {
    'stage': BillingStageRef;
    'model': ModelReference | null;
    'billing': BilledTokenCounts;
    /**
     * Wall-clock runtime in seconds.
     */
    'runtime_secs': number;
    /**
     * Wall-clock time the latest attempt of this stage started, if known.
     */
    'started_at'?: string | null;
    /**
     * Lifecycle state of the stage. Use to detect in-flight rows for client-side runtime ticking.
     */
    'state'?: StageState | null;
}
