/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunControlOutcome } from './run-control-outcome';

/**
 * The worker\'s answer to a steer or an interrupt, as the endpoint\'s `202` body.
 */
export interface RunControlAcknowledgement {
    'outcome': RunControlOutcome;
    /**
     * The label of the stage the control was delivered to (`node@visit`, or `node/e<execution>@visit`); absent when the outcome is `pending`.
     */
    'stage'?: string;
}
