/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Which item shape a run stream item carries.
 */

export const RunStreamItemKind = {
    PETRI: 'petri',
    PLATFORM: 'platform'
} as const;

export type RunStreamItemKind = typeof RunStreamItemKind[keyof typeof RunStreamItemKind];
