/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * What became of a forwarded control: `delivered` once the worker delivered it to its stage; `pending` when the worker gave no answer within the wait, in which case the run\'s event stream says what became of it (a `run.notice` record on refusal).
 */

export const RunControlOutcome = {
    DELIVERED: 'delivered',
    PENDING: 'pending'
} as const;

export type RunControlOutcome = typeof RunControlOutcome[keyof typeof RunControlOutcome];
