/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Resolved `[run.limits]` spend budget for the run. An absent field means that limit is not configured. When accumulated LLM spend exceeds either limit, the run halts and fails with the `budget_exhausted` failure reason.
 */
export interface RunLimitsSettings {
    /**
     * Maximum total LLM cost for the run, in USD micros.
     */
    'max_cost_usd_micros'?: number;
    /**
     * Maximum total LLM tokens for the run, counting all token buckets (input, output, reasoning, cache reads, cache writes).
     */
    'max_tokens'?: number;
}
