/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A captured workspace file with its durable payload source.
 */
export interface RunArtifact {
    /**
     * Content-addressed SHA-256 hash of a stored blob. Hex input is case-insensitive; Fabro emits the canonical lowercase form.
     */
    'blob'?: string;
    /**
     * Content-addressed SHA-256 hash of a stored blob. Hex input is case-insensitive; Fabro emits the canonical lowercase form.
     */
    'object'?: string;
    /**
     * Canonical stage execution identifier in `node_id@visit` form.
     */
    'stage_id': string;
    'retry': number;
    'relative_path': string;
    'size': number;
}
