/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ForkOrigin } from './fork-origin';
// May contain unused imports in some cases
// @ts-ignore
import type { TimelineEntryResponse } from './timeline-entry-response';

/**
 * The run\'s checkpoints in order, and its fork origin when it is a fork.
 */
export interface RunTimelineResponse {
    'entries': Array<TimelineEntryResponse>;
    'forked_from'?: ForkOrigin | null;
}
