/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * How a sandbox network allow/block rule set is represented.
 */

export const SandboxNetworkRuleSetMode = {
    UNKNOWN: 'unknown',
    NONE: 'none',
    ALL: 'all',
    CIDRS: 'cidrs',
    ESSENTIALS: 'essentials'
} as const;

export type SandboxNetworkRuleSetMode = typeof SandboxNetworkRuleSetMode[keyof typeof SandboxNetworkRuleSetMode];
