/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * What a session event records.
 */

export const SessionEventName = {
    RUN_SESSION_CREATED: 'run.session.created',
    RUN_SESSION_TURN_STARTED: 'run.session.turn.started',
    RUN_SESSION_USER_MESSAGE: 'run.session.user_message',
    RUN_SESSION_ASSISTANT_DELTA: 'run.session.assistant_delta',
    RUN_SESSION_ASSISTANT_MESSAGE: 'run.session.assistant_message',
    RUN_SESSION_TOOL_CALL_STARTED: 'run.session.tool_call.started',
    RUN_SESSION_TOOL_CALL_COMPLETED: 'run.session.tool_call.completed',
    RUN_SESSION_TURN_SUCCEEDED: 'run.session.turn.succeeded',
    RUN_SESSION_TURN_FAILED: 'run.session.turn.failed',
    RUN_SESSION_TURN_INTERRUPTED: 'run.session.turn.interrupted'
} as const;

export type SessionEventName = typeof SessionEventName[keyof typeof SessionEventName];
