/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionEventName } from './session-event-name';

/**
 * One recorded event of an Ask Fabro session: its position in the session (`seq`, from 1), the session and run it belongs to, when it was recorded, the event\'s name and its properties. Every event but `run.session.created` carries the `turn_id` it belongs to in its properties.
 */
export interface SessionEvent {
    'seq': number;
    /**
     * Durable session identifier.
     */
    'session_id': string;
    'run_id': string;
    'ts': string;
    'event': SessionEventName;
    'properties': { [key: string]: any; };
}
