/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommandTermination } from './command-termination';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeStatusRecord } from './node-status-record';

/**
 * Internal stage projection state.
 */
export interface StageState {
    /**
     * Event-log sequence number of the first event that created this stage. Used to order stages by execution.
     */
    'seq'?: number;
    'prompt'?: string | null;
    'response'?: string | null;
    'status'?: NodeStatusRecord | null;
    /**
     * Provider and model metadata recorded for the stage attempt.
     */
    'provider_used'?: object | null;
    'diff'?: string | null;
    /**
     * Command and environment recorded when the stage script ran.
     */
    'script_invocation'?: object | null;
    /**
     * Wall-clock and step timing metadata for the stage script.
     */
    'script_timing'?: object | null;
    /**
     * Per-branch result objects produced by a parallel stage.
     */
    'parallel_results'?: Array<object> | null;
    'stdout'?: string | null;
    'stderr'?: string | null;
    'stdout_bytes'?: number | null;
    'stderr_bytes'?: number | null;
    'streams_separated'?: boolean | null;
    'live_streaming'?: boolean | null;
    'termination'?: CommandTermination | null;
}



