/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Source of a stage's model usage metadata.
 */

export const StageModelMode = {
    PROMPT: 'prompt',
    AGENT: 'agent',
    ACP: 'acp',
    FAN_IN: 'fan_in'
} as const;

export type StageModelMode = typeof StageModelMode[keyof typeof StageModelMode];
