/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for steering a running run mid-execution.
 */
export interface SteerRunRequest {
    /**
     * The steering message text to deliver as a user turn.
     */
    'text': string;
    /**
     * When true, stop the stage\'s current model turn first and make this text its next input, in one control. When false (default), the text is guidance the agent runs as a follow-up turn once its current answer is reached.
     */
    'interrupt'?: boolean;
    /**
     * The agent stage to steer: its stage identifier (`node_id@visit`) or its node name. Omit it to steer the run\'s one live agent stage; a run with several live agent stages then refuses the steer with a `run.notice` record.
     */
    'stage'?: string;
}
