/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlockedReason } from './blocked-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusReason } from './status-reason';

/**
 * Durable run summary derived from the backing store.
 */
export interface StoreRunSummary {
    'run_id': string;
    'workflow_name'?: string | null;
    'workflow_slug'?: string | null;
    'goal'?: string | null;
    'labels': { [key: string]: string; };
    'host_repo_path'?: string | null;
    'start_time'?: string | null;
    'status': RunStatus;
    'status_reason'?: StatusReason | null;
    'blocked_reason'?: BlockedReason | null;
    'pending_control'?: RunControlAction | null;
    'duration_ms'?: number | null;
    'total_usd_micros'?: number | null;
}



