/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CPU resources visible to the Fabro server process.
 */
export interface SystemCpuResources {
    /**
     * Whether CPU metrics are available on this platform.
     */
    'supported': boolean;
    /**
     * Metric scope. Currently `server_environment`.
     */
    'scope': string;
    /**
     * Reason metrics are unavailable when unsupported.
     */
    'unavailable_reason': string | null;
    /**
     * Logical CPUs visible to the server process.
     */
    'logical_cpus': number | null;
    /**
     * CPU usage percentage, null until a delta sample is available.
     */
    'usage_percent': number | null;
    /**
     * Expected polling interval used for delta-based CPU sampling.
     */
    'sample_window_ms': number | null;
}

