/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Memory resources visible to the Fabro server process.
 */
export interface SystemMemoryResources {
    /**
     * Whether memory metrics are available on this platform.
     */
    'supported': boolean;
    /**
     * `cgroup` when Linux cgroup limits are available, otherwise `host`.
     */
    'scope': string;
    /**
     * Reason metrics are unavailable when unsupported.
     */
    'unavailable_reason': string | null;
    /**
     * Total memory for the reported scope.
     */
    'total_bytes': number | null;
    /**
     * Used memory for the reported scope.
     */
    'used_bytes': number | null;
    /**
     * Available memory for the reported scope.
     */
    'available_bytes': number | null;
    /**
     * Used memory percentage for the reported scope.
     */
    'used_percent': number | null;
    /**
     * Host total memory, included even when reporting a cgroup scope.
     */
    'host_total_bytes': number | null;
}

