/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiffSummary } from './diff-summary';

/**
 * One checkpoint of a run.
 */
export interface TimelineEntryResponse {
    /**
     * 1-based, in the order the checkpoints were recorded; the `@ordinal` a fork target names.
     */
    'ordinal': number;
    /**
     * The checkpoint record\'s position among the run\'s platform records.
     */
    'checkpoint_seq': number;
    /**
     * The Petri execution the checkpoint belongs to.
     */
    'execution': number;
    /**
     * The Petri firing the checkpoint belongs to.
     */
    'firing': number;
    /**
     * The attempt of the firing whose files the commit holds, from 1.
     */
    'attempt': number;
    /**
     * The stage id (`node@visit`) when the projection shows the stage.
     */
    'stage'?: string | null;
    'node_name': string;
    'visit': number;
    /**
     * The Petri workspace id the commit was made in.
     */
    'workspace'?: string | null;
    'run_commit_sha'?: string | null;
    'diff_summary'?: DiffSummary | null;
}
