/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about a workflow\'s most recent run.
 */
export interface WorkflowLastRun {
    /**
     * ISO 8601 timestamp of the most recent run.
     */
    'ran_at': string;
}

